CREATE DATABASE crud

CREATE  TABLE siswa(
id INT AUTO_INCREMENT KEY,
nama VARCHAR (255) NOT NULL,
kelas VARCHAR (4) NOT NULL,
jurusan VARCHAR (255) NOT NULL
)

CREATE TABLE login(
id INT AUTO_INCREMENT KEY,
username VARCHAR (255),
`password` VARCHAR (255)
)